### ISSUE TITLE
A internal error occurs  in mjsunit/es6/promises by the latest code.

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#79] opened 2020-07-28 05:30 UTC
==== C stack trace ===============================
**Describe the bug**
Hi @fw-brice , the latest code(`commit:6d9a4ef6ce25f09278828883ad26bb3b5812e19a`) in riscv-porting-dev occurs internal error in mjsunit/es6/promises.

**To Reproduce**
1. Build with options 'riscv64.sim'
2. Run test/program` ./out/riscv64.sim/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/promises.js --randomseed=1058420632 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax`
3. See error 
`
```
[23:19|%  36|+ 1821|-   1]: mjsunit/es6/promises
=== mjsunit/es6/promises ===
Warning: unknown flag --enable-slow-asserts.
Try --help for options
#
# Fatal error in ../../src/codegen/safepoint-table.cc, line 62
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffdbd921c00`
```
**Expected behavior**

**Errors/Logs**
If applicable, copy/paste the errors or log messages here.

**Additional context**

**Comment by luyahan** [comment] 2020-07-28 06:25
I revert @LOGQTAINIA  4 commit:
```
commit e044a0f5ff96b3c1349c92e624efafb50bc96dec
Author: taolq <taolq@outlook.com>
Date:   Sat Jul 25 04:52:32 2020 +0300

    rename with intuitive names

commit ba0ff6275274688b7374eccccfaf741be257b50b
Author: taolq <taolq@outlook.com>
Date:   Fri Jul 24 09:58:09 2020 +0300

    Add tbreak command & fix break command in simulator

commit cc689b442e66d938c9fd05bef498949e14b8ad43
Author: taolq <taolq@outlook.com>
Date:   Thu Jul 23 14:37:29 2020 +0300

    remove unused code for break command in simulator

commit 04997b86bc7af0143b78698665af8d63f8b265c4
Author: taolq <taolq@outlook.com>
Date:   Thu Jul 23 09:52:19 2020 +0300

    Fix break command in simulator
```
it is ok, but i revert 
```
commit 6d9a4ef6ce25f09278828883ad26bb3b5812e19a (HEAD -> fix-#79, rios-v8-riscv/riscv-porting-dev)
Author: zouxiaofang@iscas.ac.cn <zouxiaofang@iscas.ac.cn>
Date:   Mon Jul 27 01:07:27 2020 +0000

    Optimize TurboAssembler::Ext32
    when size is 32, it will generate following two instructions:
    1. slliw rt, rs, 0
    2. srliw rt, rt, 0
    The first instruction with a zero shift amount truncates a 64-bit value to 32
    bits and sign-extends it. The second instruction with a zero shift amount is
    redundant.
```
it's also ok.

**Comment by luyahan** [comment] 2020-07-28 06:56
- Build the latest code(commit:6d9a4ef6ce25f09278828883ad26bb3b5812e19a) 
- run  ` ./out/riscv64.debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/promises.js --randomseed=1058420632 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax` on qemu. It's also ok.

**Comment by luyahan** [comment] 2020-07-28 07:22
error occurs in CI:https://github.com/v8-riscv/v8/runs/917239009?check_suite_focus=true

**Comment by luyahan** [comment] 2020-07-28 07:43
I run twice, one is normal, one is failed.
```
user@d0486de898ae:~/v8-riscv64 $ ./out/riscv64.debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/promises.js --random-seed=1058420632 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax


#
# Fatal error in ../../src/codegen/safepoint-table.cc, line 62
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffdd30c7210
==== C stack trace ===============================

    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8_libbase.so(v8::base::debug::StackTrace::StackTrace()+0x21) [0x7f8779d91a81]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8_libplatform.so(+0x45fea) [0x7f8779d1efea]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8_libbase.so(V8_Fatal(char const*, int, char const*, ...)+0x26e) [0x7f8779d7a83e]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::SafepointTable::FindEntry(unsigned long) const+0x1e6) [0x7f8778483576]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Code::GetSafepointEntry(unsigned long)+0x79) [0x7f87789794b9]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::StandardFrame::IterateCompiledFrame(v8::internal::RootVisitor*) const+0x2df) [0x7f87785ad9df]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::OptimizedFrame::Iterate(v8::internal::RootVisitor*) const+0x20) [0x7f87785ae470]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Isolate::Iterate(v8::internal::RootVisitor*, v8::internal::ThreadLocalTop*)+0x372) [0x7f87785be982]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Isolate::Iterate(v8::internal::RootVisitor*)+0x43) [0x7f87785bea53]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::IterateStrongRoots(v8::internal::RootVisitor*, v8::internal::VisitMode)+0x105) [0x7f87786c2e25]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::IterateRoots(v8::internal::RootVisitor*, v8::internal::VisitMode)+0x2a) [0x7f87786bf1fa]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::Verify()+0x122) [0x7f87786b10d2]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::GarbageCollectionPrologue()+0x1d6) [0x7f87786b0d56]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)+0x362) [0x7f87786b5182]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)+0x126) [0x7f87786c4ac6]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)+0x59) [0x7f87786c4c29]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::HeapObject v8::internal::Heap::AllocateRawWith<(v8::internal::Heap::AllocationRetryMode)1>(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)+0x2a0) [0x7f877867c5e0]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment)+0x40) [0x7f877865e620]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::FactoryBase<v8::internal::Factory>::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment)+0x32) [0x7f877865acb2]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment)+0x3a) [0x7f8778658baa]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType)+0x1fb) [0x7f8778658f3b]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::IncrementalStringBuilder::Extend()+0x13b) [0x7f8778f06efb]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(void v8::internal::IncrementalStringBuilder::Append<unsigned char, unsigned char>(unsigned char)+0x1a4) [0x7f87783334b4]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::IncrementalStringBuilder::AppendCharacter(unsigned char)+0x2f) [0x7f87783b79bf]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::MessageFormatter::Format(v8::internal::Isolate*, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>)+0x225) [0x7f87785fc115]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(+0x238c47b) [0x7f87785fe47b]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode)+0xbc) [0x7f87785fe1ec]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Factory::NewError(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0x182) [0x7f877866a202]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Factory::NewTypeError(v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0x6b) [0x7f877866a5fb]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(+0x214a2f8) [0x7f87783bc2f8]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Builtin_StrictPoisonPillThrower(int, unsigned long*, v8::internal::Isolate*)+0xfe) [0x7f87783bc02e]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::SoftwareInterrupt()+0xa0c) [0x7f87791f7ebc]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::DecodeRVIType()+0xe75) [0x7f87791fee75]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::InstructionDecode(v8::internal::Instruction*)+0x21b) [0x7f87791f4edb]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::Execute()+0xb5) [0x7f87791ffc25]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::CallInternal(unsigned long)+0x2da) [0x7f87791fff2a]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Simulator::CallImpl(unsigned long, int, long const*)+0x39e) [0x7f877920092e]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(unsigned long v8::internal::SimulatorBase::VariadicCall<unsigned long, v8::internal::Simulator, long (v8::internal::Simulator::*)(unsigned long, int, long const*), unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**>(v8::internal::Simulator*, long (v8::internal::Simulator::*)(unsigned long, int, long const*), unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**)+0x1ac) [0x7f87785a988c]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(unsigned long v8::internal::Simulator::Call<unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**>(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**)+0xa1) [0x7f87785a96d1]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::GeneratedCode<unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**>::Call(unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**)+0x71) [0x7f87785a93a1]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(+0x2334af4) [0x7f87785a6af4]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*)+0x91) [0x7f87785a5cb1]
    /home/user/v8/v8.snapshot-20200531/v8-cr/v8/out/riscv64.debug/libv8.so(v8::Script::Run(v8::Local<v8::Context>)+0x404) [0x7f87782027c4]
    ./out/riscv64.debug/d8(v8::Shell::ExecuteString(v8::Isolate*, v8::Local<v8::String>, v8::Local<v8::Value>, v8::Shell::PrintResult, v8::Shell::ReportExceptions, v8::Shell::ProcessMessageQueue)+0xb41) [0x5610d9f8bf91]
    ./out/riscv64.debug/d8(v8::SourceGroup::Execute(v8::Isolate*)+0x40e) [0x5610d9f997fe]
    ./out/riscv64.debug/d8(v8::Shell::RunMain(v8::Isolate*, int, char**, bool)+0x1eb) [0x5610d9f9c39b]
    ./out/riscv64.debug/d8(v8::Shell::Main(int, char**)+0x1018) [0x5610d9f9d7c8]
    ./out/riscv64.debug/d8(main+0x22) [0x5610d9f9dc92]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f8775541b97]
    ./out/riscv64.debug/d8(_start+0x2a) [0x5610d9f72eea]
Received signal 6
Aborted (core dumped)
user@d0486de898ae:~/v8-riscv64 $ ./out/riscv64.debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/promises.js --random-seed=1058420632 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
new-throw succeeded
resolved/then succeeded
rejected/then succeeded
then/resolve succeeded
then/resolve succeeded
then/reject succeeded
then/reject succeeded
then/reject2 succeeded
then/reject2 succeeded
cyclic/deferred/then succeeded
cyclic/deferred/then succeeded
all/resolve/empty succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
resolve-with-thenable succeeded
resolved/then-nohandler succeeded
resolved/then-nohandler-undefined succeeded
resolved/then-nohandler-null succeeded
resolved/then/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
then/resolve-non-function succeeded
then/reject-non-function succeeded
cyclic/then succeeded
cyclic/then succeeded
all/resolve/iterable succeeded
all/resolve/iterable/0 succeeded
all/resolve/iterable/1 succeeded
all/resolve/iterable/2 succeeded
all/resolve succeeded
all/resolve/0 succeeded
all/resolve/1 succeeded
all/resolve/2 succeeded
all/reject succeeded
all/iterable/number/length succeeded
all/iterable/number/0 succeeded
all/iterable/number/1 succeeded
all/iterable/number/2 succeeded
resolved/one succeeded
resolved-const/one succeeded
one/resolve succeeded
resolved/one succeeded
one/resolve/reject succeeded
one/reject/resolve succeeded
race/iterable/resolve/reject succeeded
race/iterable/reject/resolve succeeded
race/iterable/number succeeded
then/resolve2 succeeded
then/resolve2 succeeded
resolved/then/then2 succeeded
resolved/thenable/then succeeded
resolved/thenable/then succeeded
rejected/thenable/then succeeded
rejected/thenable/then succeeded
then/resolve/thenable succeeded
then/resolve/thenable succeeded
then/reject/thenable succeeded
then/reject/thenable succeeded
then/resolve/thenable2 succeeded
then/resolve/thenable2 succeeded
resolve-with-thenable2 succeeded
all succeeded
user@d0486de898ae:~/v8-riscv64 $
```

**Comment by amyzxf** [comment] 2020-07-28 08:00
> I run twice, one is normal, one is failed.
> user@d0486de898ae:~/v8-riscv64 $ ./out/riscv64.debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/promises.js --random-seed=1058420632 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax

It's the same on my side,  sometimes it reports wrong, sometimes it's successful.

**Comment by thomasyonug** [comment] 2020-07-28 08:25
It works very well on my physical machine.

`abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
Warning: unknown flag --randomseed=1058420632.
Try --help for options
Warning: unknown flag --enable-slow-asserts.
Try --help for options
new-throw succeeded
resolved/then succeeded
rejected/then succeeded
then/resolve succeeded
then/resolve succeeded
then/reject succeeded
then/reject succeeded
then/reject2 succeeded
then/reject2 succeeded
cyclic/deferred/then succeeded
cyclic/deferred/then succeeded
all/resolve/empty succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
all/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
race/non iterable succeeded
resolve-with-thenable succeeded
resolved/then-nohandler succeeded
resolved/then-nohandler-undefined succeeded
resolved/then-nohandler-null succeeded
resolved/then/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
resolved/then-throw/then succeeded
then/resolve-non-function succeeded
then/reject-non-function succeeded
cyclic/then succeeded
cyclic/then succeeded
all/resolve/iterable succeeded
all/resolve/iterable/0 succeeded
all/resolve/iterable/1 succeeded
all/resolve/iterable/2 succeeded
all/resolve succeeded
all/resolve/0 succeeded
all/resolve/1 succeeded
all/resolve/2 succeeded
all/reject succeeded
all/iterable/number/length succeeded
all/iterable/number/0 succeeded
all/iterable/number/1 succeeded
all/iterable/number/2 succeeded
resolved/one succeeded
resolved-const/one succeeded
one/resolve succeeded
resolved/one succeeded
one/resolve/reject succeeded
one/reject/resolve succeeded
race/iterable/resolve/reject succeeded
race/iterable/reject/resolve succeeded
race/iterable/number succeeded
then/resolve2 succeeded
then/resolve2 succeeded
resolved/then/then2 succeeded
resolved/thenable/then succeeded
resolved/thenable/then succeeded
rejected/thenable/then succeeded
rejected/thenable/then succeeded
then/resolve/thenable succeeded
then/resolve/thenable succeeded
then/reject/thenable succeeded
then/reject/thenable succeeded
then/resolve/thenable2 succeeded
then/resolve/thenable2 succeeded
resolve-with-thenable2 succeeded
all succeeded`

**Comment by fw-brice** [comment] 2020-07-28 13:07
Duplicate of #56

**Closed** 2020-07-28 13:07 UTC
Labels: bug
