### ISSUE TITLE
Not Instance of Error: in `test/mjsunit/mjsunit.js:315`

### ISSUE THREAD

**Issue by derekzTu** [v8-riscv/v8#86] opened 2020-07-29 22:02 UTC
**Describe the bug**
Running `test/mjsunit/harmony/object-fromentries.js` triggers a not instance of error

**To Reproduce**
1. Build release build (see instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build))
2. Run program:
```bash
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/harmony/object-fromentries.js --random-seed=-534112441 --stress-opt --always-opt --no-liftoff --stress-lazy-source-positions --nohard-abort --testing-d8-test-runner
```
3. See error
```bash
============ Stress 1/5 ============
/root/home/v8_root/v8/test/mjsunit/mjsunit.js:315: Object <Error(Error: IteratorClose must not be performed if IteratorStep throws)> is not an instance of <ThrewDuringIteratorNext> but of <Error>

Stack: MjsUnitAssertionError
    at assertThrows                         /root/home/v8_root/v8/test/mjsunit/mjsunit.js 510:7
    at Object.exceptionIfIteratorNextThrows /root/home/v8_root/v8/test/mjsunit/harmony/object-fromentries.js 76:5
    at                                      /root/home/v8_root/v8/test/mjsunit/harmony/object-fromentries.js 436:10
    throw new MjsUnitAssertionError(message);
    ^
MjsUnitAssertionError
    at assertThrows                         /root/home/v8_root/v8/test/mjsunit/mjsunit.js 510:7
    at Object.exceptionIfIteratorNextThrows /root/home/v8_root/v8/test/mjsunit/harmony/object-fromentries.js 76:5
    at                                      /root/home/v8_root/v8/test/mjsunit/harmony/object-fromentries.js 436:10

======== Full Deoptimization =======
```

**Expected behavior**
No error log shown

**Comment by penguinwu** [comment] 2020-08-04 01:39
Look like duplicate of #82

**Comment by luyahan** [comment] 2020-08-12 02:57
On the lastedt commit, the test case pass. @derekzTu

**Closed** 2020-08-12 14:16 UTC
Labels: bug
