### ISSUE TITLE
release build: src/codegen/riscv64/assembler-riscv64-inl.h:197:11: error: unused variable 'instr' [-Werror,-Wunused-variable]

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#111] opened 2020-08-05 02:33 UTC
**Describe the bug**

error: unused variable 'instr' [-Werror,-Wunused-variable]

Build Error 

**To Reproduce**

1. follow https://github.com/v8-riscv/v8/wiki/get-the-source
2. follow https://github.com/v8-riscv/v8/wiki/simulator-build
3. run `tools/dev/gm.py riscv64.release`

**Expected behavior**

Build succeed

**Errors/Logs**
```
[26/1026] CXX obj/v8_base_without_compiler/compiler.o
FAILED: obj/v8_base_without_compiler/compiler.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/v8_base_without_compiler/compiler.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n362116-1bd7046e-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=d6879d611f3dcf3da8dd92e080029394aa30bc42 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_DISASSEMBLER -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DOBJECT_PRINT -DVERIFY_HEAP -DV8_INTL_SUPPORT -DENABLE_HANDLE_ZAPPING -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_CONCURRENT_MARKING -DV8_ENABLE_LAZY_SOURCE_POSITIONS -DV8_EMBEDDED_BUILTINS -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DV8_IMMINENT_DEPRECATION_WARNINGS -D_MIPS_TARGET_SIMULATOR -DV8_TARGET_ARCH_RISCV64 -D__riscv_xlen=64 -DCAN_USE_FPU_INSTRUCTIONS -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DV8_IMMINENT_DEPRECATION_WARNINGS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DV8_IMMINENT_DEPRECATION_WARNINGS -I../.. -Igen -I../.. -Igen -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../include -I../../third_party/zlib -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wmissing-field-initializers -Wunreachable-code -Wshorten-64-to-32 -O3 -fno-ident -fdata-sections -ffunction-sections -fvisibility=default -Wexit-time-destructors -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -c ../../src/codegen/compiler.cc -o obj/v8_base_without_compiler/compiler.o
In file included from ../../src/codegen/compiler.cc:15:
In file included from ../../src/codegen/assembler-inl.h:27:
../../src/codegen/riscv64/assembler-riscv64-inl.h:197:11: error: unused variable 'instr' [-Werror,-Wunused-variable]
    Instr instr = Assembler::instr_at(pc_ + 0 * kInstrSize);
          ^
1 error generated.
[40/1026] CXX obj/torque_generated_initializers/typed-array-tq-csa.o
ninja: build stopped: subcommand failed.
Error! - V8 compilation finished with errors.

```

**Additional context**
```
wuwei@ci-v8-riscv:~/v8-cr/v8$ git log -1
commit 9b902c290c364e4bb25315f440a0d7f2086ff2c4 (HEAD -> riscv-porting-dev, riscv/riscv-porting-dev)
Author: Derek Tu <derek.t@rioslab.org>
Date:   Sat Aug 1 19:55:43 2020 +0000

    Remove is_intN checks for DropAndRet

    Removes the is_intN checks for DropAndRet because we now use the
    TurboAssembler macro Add64(...) to help deal with larger immediate
    values given.

    Resolves #84
```

**Comment by penguinwu** [comment] 2020-08-05 14:56
Duplicate of #103 (already fixed).

**Closed by penguinwu** 2020-08-05 14:56 UTC
Labels: bug
