### ISSUE TITLE
internal error: cctest/test-run-machops.cc 2233

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#73] opened 2020-07-27 07:06 UTC
**Describe the bug**
Run test case failed

**To Reproduce**
1. Build with options 'riscv64.native.release'
2. Run test/program 'python2 ./tools/run-tests.py --outdir=./ cctest' on `hifive unleashed`
3. See error

**Expected behavior**
not error occurs

**Errors/Logs**
```
=== cctest/test-run-machops/RunUint32MulHighP ===
#
# Fatal error in ../../test/cctest/compiler/test-run-machops.cc, line 2233
# Check failed: expected == bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j)) (-2 vs. 4294967294).
#
#
#
#FailureMessage Object: 0x3fffc05b88
```

**Additional context**

**Comment by penguinwu** [comment] 2020-07-29 17:47
Assigning it to Derek (but if someone is already working on this issue, do comment here).

@derekzTu first try if this test fails in QEMU or not. To reproduce this error, you can run the specific test alone using `cctest`, i.e., 
```
out.gn/riscv.debug/cctest test-run-machops/RunUint32MulHighP
```

Please follow the "how to debug" wiki on tips of debugging at the cctest level. Since this test passes in simulated build, but fails in native run, one possibility is that some of the instructions generated for Uint32MulHighP may be simulated incorrectly in the V8 Simulator. One suggestion is to compare the execution of simulated build and native-run to see where the values differ.

**Comment by luyahan** [comment] 2020-07-30 02:05
I alter code 
```
TEST(RunUint32MulHighP) {
  RawMachineAssemblerTester<int32_t> m;
  Int32BinopTester bt(&m);
  bt.AddReturn(m.Uint32MulHigh(bt.param0, bt.param1));
  uint32_t i = 4294967295, j = 4294967295;
  int32_t expected = bit_cast<int32_t>(static_cast<uint32_t>(
      (static_cast<uint64_t>(i) * static_cast<uint64_t>(j)) >> 32));
  std::cout << expected << "," << bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j))
            << "," << i << "," << j << std::endl;
  std::cout << sizeof(expected) << "," << sizeof(bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j))) << std::endl;
  auto c = bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j));
  CHECK_EQ(expected, bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j)));
}
```

In x86 by smiulator out log:
```
-2,-2,4294967295,4294967295
4,4
```

in hifive-unleashed:
```
-2,4294967294,4294967295,4294967295
4,4
```

**Comment by luyahan** [comment] 2020-07-30 08:04
```
TEST(RunUint32MulHighP) {
  RawMachineAssemblerTester<int32_t> m;
  Int32BinopTester bt(&m);
  bt.AddReturn(m.Uint32MulHigh(bt.param0, bt.param1));
  uint32_t i = 4294967295, j = 4294967295;
  int32_t expected = bit_cast<int32_t>(static_cast<uint32_t>(
      (static_cast<uint64_t>(i) * static_cast<uint64_t>(j)) >> 32));
  std::cout << expected << "," << bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j))
            << "," << i << "," << j << std::endl;
  std::cout << sizeof(expected) << "," << sizeof(bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j))) << std::endl;
  int32_t result = bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j));
  std::cout << "result:" << result << std::endl;
  CHECK_EQ(expected, bt.call(bit_cast<int32_t>(i), bit_cast<int32_t>(j)));
}
```
```
-2,4294967294,4294967295,4294967295
4,4
result:4294967294
```

**Comment by luyahan** [comment] 2020-07-30 09:10
I guess i know why it. Because bt.call is code gen and Uint32MulHigh set uint32_t num to a0 but don't signed extened the a0. so result  get a uint32_t value(not signed extened).

**Comment by luyahan** [comment] 2020-07-31 00:47
@penguinwu @derekzTu i had fix it and pull request.

**Closed** 2020-07-31 17:58 UTC
Labels: bug
