### ISSUE TITLE
Assertion failure for `test/mjsunit/compiler/dataview-detached.js`

### ISSUE THREAD

**Issue by LOGQTAINIA** [v8-riscv/v8#149] opened 2020-08-13 02:11 UTC
**Describe the bug**
Running `test/mjsunit/compiler/dataview-detached.js` results in an assertion failure.

This bug shows up in #130 , but it could be triggered in simulated build now.

It is caused by nan-boxing PR. 

**To Reproduce**
1. Build with options `riscv64.sim`
2. Run test/program 
```
out/riscv64.sim/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compiler/dataview-detached.js --random-seed=-1109454776 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax --opt --noalways-opt --no-stress-flush-bytecode
```
3. See error

**Expected behavior**

**Errors/Logs**
```
/home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/mjsunit.js:315: Failure: expected <0> found <NaN>

Stack: MjsUnitAssertionError
    at assertEquals /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/mjsunit.js 405:7
    at              /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/compiler/dataview-detached.js 164:3
    at              /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/compiler/dataview-detached.js 176:3
    throw new MjsUnitAssertionError(message);
    ^
MjsUnitAssertionError
    at assertEquals /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/mjsunit.js 405:7
    at              /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/compiler/dataview-detached.js 164:3
    at              /home/user/v8.snapshot-20200531/v8-cr/v8/test/mjsunit/compiler/dataview-detached.js 176:3
```

**Additional context**

**Comment by penguinwu** [comment] 2020-08-13 22:13
Duplicate of #113. Fix ready to be checked-in.

**Closed by penguinwu** 2020-08-13 22:13 UTC
Labels: bug
