### ISSUE TITLE
[RISCV64 Branch][QEMU 5.0.0] cctest/test-cpu-profiler/DeoptAtSecondLevelInlinedSource failed

### ISSUE THREAD

**Issue by LOGQTAINIA** [v8-riscv/v8#194] opened 2020-08-23 07:01 UTC
**Describe the bug**

**To Reproduce**
1. Build with options `riscv64.native.debug`
2. Run test/program `riscv64.native.debug/cctest test-cpu-profiler/DeoptAtSecondLevelInlinedSource --random-seed=138862460 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner`
3. See error

**Expected behavior**

**Errors/Logs**
```
=== cctest/test-cpu-profiler/DeoptAtSecondLevelInlinedSource ===
--- stderr ---
#
# Fatal error in ../../src/execution/frames.h, line 154
# Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (137434871968 vs. 23).
#
#
#
#FailureMessage Object: 0x3fff835e78
==== C stack trace ===============================

    /home/riscv/riscv64.native.debug/cctest(+0x340e048) [0x2aae976048]
    /home/riscv/riscv64.native.debug/cctest(+0x33649f2) [0x2aae8cc9f2]
    /home/riscv/riscv64.native.debug/cctest(+0x314e362) [0x2aae6b6362]
    /home/riscv/riscv64.native.debug/cctest(+0x314e38c) [0x2aae6b638c]
    /home/riscv/riscv64.native.debug/cctest(+0x12701da) [0x2aac7d81da]
    /home/riscv/riscv64.native.debug/cctest(+0x126b1c2) [0x2aac7d31c2]
    /home/riscv/riscv64.native.debug/cctest(+0x126b25e) [0x2aac7d325e]
    /home/riscv/riscv64.native.debug/cctest(+0x126b2f8) [0x2aac7d32f8]
    /home/riscv/riscv64.native.debug/cctest(+0x17469d0) [0x2aaccae9d0]
    /home/riscv/riscv64.native.debug/cctest(+0x1747050) [0x2aaccaf050]
    /home/riscv/riscv64.native.debug/cctest(+0x1716e4c) [0x2aacc7ee4c]
    /home/riscv/riscv64.native.debug/cctest(+0x1abb710) [0x2aad023710]
    /home/riscv/riscv64.native.debug/cctest(+0x1abb794) [0x2aad023794]
    linux-vdso.so.1(__vdso_rt_sigreturn+0) [0x3ff7d41800]
    /home/riscv/riscv64.native.debug/cctest(+0x12075ac) [0x2aac76f5ac]                                                                                    /home/riscv/riscv64.native.debug/cctest(+0x12076b2) [0x2aac76f6b2]
    /home/riscv/riscv64.native.debug/cctest(+0x121449a) [0x2aac77c49a]
    /home/riscv/riscv64.native.debug/cctest(+0x1214e1a) [0x2aac77ce1a]
    [0xd894434d0]
Command: /home/riscv/riscv64.native.debug/cctest test-cpu-profiler/DeoptAtSecondLevelInlinedSource --random-seed=138862460 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner

```

**Additional context**

**Comment by penguinwu** [comment] 2020-08-24 16:05
Look like duplicate of #192, close this one.

**Closed by penguinwu** 2020-08-24 16:05 UTC
Labels: bug
