### ISSUE TITLE
[RISCV64 Branch][QEMU 5.0.0] cctest/test-cpu-profiler/DeoptAtFirstLevelInlinedSource failed

### ISSUE THREAD

**Issue by LOGQTAINIA** [v8-riscv/v8#193] opened 2020-08-23 06:59 UTC
**Describe the bug**

**To Reproduce**
1. Build with options `riscv64.native.debug`
2. Run test/program `riscv64.native.debug/cctest test-cpu-profiler/DeoptAtFirstLevelInlinedSource --random-seed=138862460 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner`
3. See error

**Expected behavior**

**Errors/Logs**
```
=== cctest/test-cpu-profiler/DeoptAtFirstLevelInlinedSource ===
--- stderr ---
#
# Fatal error in ../../src/execution/frames.h, line 154
# Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (137436278968 vs. 23).
#
#
#
#FailureMessage Object: 0x3fffae5068
==== C stack trace ===============================

    /home/riscv/riscv64.native.debug/cctest(+0x340e048) [0x2ac553c048]
    /home/riscv/riscv64.native.debug/cctest(+0x33649f2) [0x2ac54929f2]
    /home/riscv/riscv64.native.debug/cctest(+0x314e362) [0x2ac527c362]
    /home/riscv/riscv64.native.debug/cctest(+0x314e38c) [0x2ac527c38c]
    /home/riscv/riscv64.native.debug/cctest(+0x12701da) [0x2ac339e1da]
    /home/riscv/riscv64.native.debug/cctest(+0x126b1c2) [0x2ac33991c2]
    /home/riscv/riscv64.native.debug/cctest(+0x126b25e) [0x2ac339925e]
    /home/riscv/riscv64.native.debug/cctest(+0x126b2f8) [0x2ac33992f8]
    /home/riscv/riscv64.native.debug/cctest(+0x17469d0) [0x2ac38749d0]
    /home/riscv/riscv64.native.debug/cctest(+0x1747050) [0x2ac3875050]
    /home/riscv/riscv64.native.debug/cctest(+0x1716e4c) [0x2ac3844e4c]
    /home/riscv/riscv64.native.debug/cctest(+0x1abb710) [0x2ac3be9710]
    /home/riscv/riscv64.native.debug/cctest(+0x1abb794) [0x2ac3be9794]
    linux-vdso.so.1(__vdso_rt_sigreturn+0) [0x3fc5da5800]
    /home/riscv/riscv64.native.debug/cctest(+0x1202c28) [0x2ac3330c28]
    /home/riscv/riscv64.native.debug/cctest(+0x1214d34) [0x2ac3342d34]
    [0xd894434d0]
Command: /home/riscv/riscv64.native.debug/cctest test-cpu-profiler/DeoptAtFirstLevelInlinedSource --random-seed=138862460 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner
```

**Additional context**

**Comment by penguinwu** [comment] 2020-08-24 16:05
Look like duplicate of #192, close this one.

**Closed by penguinwu** 2020-08-24 16:05 UTC
Labels: bug
